set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(RR_LINUX_AARCH64_TRIPLE "aarch64-linux-gnu" CACHE STRING "GNU target triple for Linux ARM64 cross builds.")

find_program(RR_LINUX_AARCH64_CC NAMES ${RR_LINUX_AARCH64_TRIPLE}-gcc REQUIRED)
find_program(RR_LINUX_AARCH64_CXX NAMES ${RR_LINUX_AARCH64_TRIPLE}-g++ REQUIRED)
find_program(RR_LINUX_AARCH64_AR NAMES ${RR_LINUX_AARCH64_TRIPLE}-ar)
find_program(RR_LINUX_AARCH64_RANLIB NAMES ${RR_LINUX_AARCH64_TRIPLE}-ranlib)
find_program(RR_LINUX_AARCH64_STRIP NAMES ${RR_LINUX_AARCH64_TRIPLE}-strip)

set(CMAKE_C_COMPILER "${RR_LINUX_AARCH64_CC}")
set(CMAKE_CXX_COMPILER "${RR_LINUX_AARCH64_CXX}")
set(CMAKE_ASM_COMPILER "${RR_LINUX_AARCH64_CC}")
set(CMAKE_C_COMPILER_TARGET "${RR_LINUX_AARCH64_TRIPLE}")
set(CMAKE_CXX_COMPILER_TARGET "${RR_LINUX_AARCH64_TRIPLE}")

if(RR_LINUX_AARCH64_AR)
	set(CMAKE_AR "${RR_LINUX_AARCH64_AR}")
endif()
if(RR_LINUX_AARCH64_RANLIB)
	set(CMAKE_RANLIB "${RR_LINUX_AARCH64_RANLIB}")
endif()
if(RR_LINUX_AARCH64_STRIP)
	set(CMAKE_STRIP "${RR_LINUX_AARCH64_STRIP}")
endif()

list(APPEND CMAKE_SYSTEM_LIBRARY_PATH
	"/usr/lib/${RR_LINUX_AARCH64_TRIPLE}"
	"/lib/${RR_LINUX_AARCH64_TRIPLE}"
)
list(APPEND CMAKE_SYSTEM_INCLUDE_PATH
	"/usr/include/${RR_LINUX_AARCH64_TRIPLE}"
)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)
